apiVersion: v1
kind: Service
metadata:
  name: argocd-server-lb
  namespace: argocd
  labels:
    app: argocd-server-lb
spec:
  selector:
    app.kubernetes.io/name: argocd-server  # The selector, it uses the service to know which pod to send the traffic to
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080

  type: LoadBalancer
