apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/johalduran7/EKS-prometheus-grafana.git
    path: app/k8s
    targetRevision: master
    helm:
      values: |
        replicaCount: 1
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-grafana-k8s
  syncPolicy:
    automated:
      prune: true  # Automatically delete or
      selfHeal: true # Fix any probelms
